[web]
address = ":8080"

[docker]
domain = "docker.localhost"
watch = true
endpoint = "unix:///var/run/docker.sock"


defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    CertFile = "/certs/auth.localhost.demo.university-cert.pem"
    KeyFile  = "/certs/auth.localhost.demo.university-key.pem"
    [[entryPoints.https.tls.certificates]]
    CertFile = "/certs/idp.localhost.demo.university-cert.pem"
    KeyFile = "/certs/idp.localhost.demo.university-key.pem"
    [[entryPoints.https.tls.certificates]]
    CertFile = "/certs/sp.localhost.federated-example.org-cert.pem"
    KeyFile = "/certs/sp.localhost.federated-example.org-key.pem"







